### ISSUE TITLE
Important usage of processors

### ISSUE THREAD

**Issue by iaeiou** [flozz/yoga-image-optimizer#11] opened 2021-08-30 01:43 UTC
### Bug description

I installed Yoga from Flatpak, then run a little test with 3 pictures, 6MB in total

#### What happened

A lot of resources are used by Yoga:

![Capture d’écran de 2021-08-30 03-37-23](https://user-images.githubusercontent.com/69427615/131273773-6dea1463-d011-446c-b5e4-f97074321a77.png)

After a few minutes, I had to kill the process

#### What was expected

Optimize the pictures and keep the computer usable ;)

### System information

* Operating system (with version): Debian 10

* How did you installed the software?

https://flathub.org/apps/details/org.flozz.yoga-image-optimizer

* YOGA Image Optimizer version:

Version 1.0.0

### Additional infos

I'm not familiar with Flatpak, is there a way to get relevant logs to report here?

**Comment by flozz** [comment] 2021-08-30 10:47
Hello,

It is not a bug: this level of optimization is a very heavy process (especially for JPEGs as Guetzli is really resources greedy). For your information, JPEG optimization takes, depending on the input image:

* 1 to 5 minute per megapixel
* 200 to 400 MB per megapixel

PNG optimization is lighter. More information here (it is in French, but Google Translate should help):

* https://blog.flozz.fr/2021/06/14/optimisez-vos-images-avec-yoga-image-optimizer/

So YOGA may not be adapted to everyone needs. Personally, I use it on "not-so-big" pictures, and generally I start an optimization batch while I do not need the PC...

The next version, that will be released soon, will improve things a little bit:

* The "Stop" button will effectively stop background threads (no more need to kill them manually),
* The number of threads used for the optimization will be configurable (so it will be possible to use only one thread to continue using the PC at the same time).

:)

**Comment by iaeiou** [comment] 2021-08-30 12:05
> It is not a bug: this level of optimization is a very heavy process

Alright, I didn't know that, thank you!

> PNG optimization is lighter. More information here (it is in French, but Google Translate should help):

No problem, I'm a native french speaker!

BTW, I discovered [imgp](https://github.com/jarun/imgp) (and [plugged it with Vscode](https://roneo.org/en/vscode-optimize-images-with-imgp/)) today. imgp is "a command line image resizer and rotator for JPEG and PNG images", maybe some interesting bits for Yoga out there?

> The next version, that will be released soon, will improve things a little bit:

Nice! Thanks for sharing this project,
cheers

**Closed** 2021-08-30 12:06 UTC
Labels: question

**Comment by flozz** [comment] 2021-08-30 12:20
> BTW, I discovered imgp (and plugged it with Vscode) today. imgp is "a command line image resizer and rotator for JPEG and PNG images", maybe some interesting bits for Yoga out there?

YOGA will not handle image rotation (it is out of its scope), but the image resize is already available on the CLI, and will be available on the GUI in the next version (YOGA Image Optimizer v1.1.0)

**Comment by licaon-kter** [comment] 2021-09-20 10:56
On Windows 1.1.0 doesn't seem to use that Setting correctly. Eg. For each file a thread is created on "Optimize" start, not when it actually processes the actual file. Making the machine behave oddly unde the load. A value of `1` yields 3 threads that use 100% of one core...each. :(

**Comment by flozz** [comment] 2021-09-23 11:08
@licaon-kter I moved your message in a new issue as it is probably not linked to this one ;)
